services:
  db:
    image: postgres:16-alpine
    container_name: usermgmt-db
    restart: unless-stopped
    
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usermgmt
      POSTGRES_USER: usermgmt
      POSTGRES_PASSWORD: usermgmt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usermgmt -d usermgmt"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  pgadmin:
   image: dpage/pgadmin4
   container_name: pgadmin4_container
   restart: always
   ports:
    - "8888:80"
   environment:
    PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
    PGADMIN_DEFAULT_PASSWORD: admin
   volumes:
    - pgadmin-data:/var/lib/pgadmin

volumes:
  dbdata:
  pgadmin-data:
