server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:usermanagement;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    # IMPORTANTISSIMO: fa partire data.sql DOPO la creazione delle tabelle JPA
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  application:
    allowedOrigins: http://localhost:[*]
    name: UserManagementDEV
management:
  endpoints:
    web:
      exposure:
        include: "*"
 
jwt:
  private.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRRGNXV29tdmxOR3lRaEEKaUIwVGNOM3NQMlZ1aFoxeE5SUHhyNThsSHN3QzlDYnRkYzJoaVNiZS9zeEF2VTFpME84dmFYd0lDZHpSWjFKTQpnMVRvaEc5emtxcWpaRGh5dzFmMUljNllSL09oRTZOQ3BxRVJ5OTdXTUZlVzZnSmQxaTVpbkhqL1cxOUdBYnFLCkxoU0hHSHFJanlvMHdsQmY1OHQrcUZ0OWgvRUZCVkUvTEFHUUJzZy9qSFVRQ3hzTG9WSTJhU0VMR0l3Mm9TREYKb2lsandMYVFsMG45a2hYNVpiaWVnTjNPa3FvZHpDWUh3V3l1NmFWVmo4TTFXOVJJTWlLbUtyMDlzL2dmMzFOYwozV2p2anFoRm8xclR1dXJXR2dLQXhKTEw3emxKcUFLakdXYklUNFA2aC8xS3d4anc2WDIzU3QzT21oc0c2SEluCitqbDErK01yQWdNQkFBRUNnZ0VCQU1mODIwd29wM3B5VU93STNhTGNhSDdZRng1VlpNenZxSmRObHZwZzFqYkUKRTJTbjY2YjF6UExOZk9JeExjQkc4eDhyOU9keTFCaTJWc3FjMC81bzNLS2ZkZ0h2bnhBQjNaM2RQaDJXQ0RlawpsQ09WQ2xFVm9MenppVHV1VGRHTzUvQ1dKWGRXSGNWeklqUHhtSzM0ZUpYaW9pTGFUWXFOM1hLcUtNZHBEMFpHCm10TlRHdkdmKzlmUTRpOTR0MFdxSXhwTXBHdDdOTTRSSHkzK09uZ2dldjB6TGlEQU5DMjNtV3JUc1VnZWN0LzcKNjJUWWc4ZzFiS3dMQWI5d0NCVCtCaU91Q2Myd3JBclJMT0pnVWtqL0Y0L2d0clI5aW1hMzRTdldVeW9VYUtBMApiaTRZQlg5bDhvSndGR0hiVTl1RkdFTW5IMFQvVjBLdElCN3FldFJleXdrQ2dZRUE5Y0Z5ZkJJUXJZSVNWL09BCitaMGJvM3ZoMmFMMFFnS3JTWFo5MjRjTHQ3aXRRQUhOWjJ5YStlM0pSbFRjemk1bW5XZmpQV1o2ZUpCLzhNbEgKR3BuMTJvL1BPRWtVK1hqWlpTUGUxUldHdDVnMFMzbFdxeXg5dG9DUzlBQ1hjTjl0R2JhcWNGU1ZJNzN6VlRSQQo4SjlnclIwZmJHbjdqYVRsVFgydG5sT1RRNjBDZ1lFQTVZallwRXE0TDhVVU1Ga3VqK0JzUzN1MG9FQm56dUhkCkk5TEVIbU4rQ01Qb3N2YWJRdTV3a0pYTHVxbzJUeFJuQXpuc0E4UjNwQ0xrZFBHb1dNQ2lXUkFzQ245NzlUZFkKUWJxTzJxdkJBRDJRMTlHdFk3bEl1NkMzNS9lblFXekpVTVFFM1dXME92akx6WjBsLzltQTJGQlJSKzNGOUExZApyQmRubXYwYzNUY0NnWUVBaTJpK2dnVlpjcVBidGdyTE9rNVdWR285RjFHcVVCdmxnTm4zMFdXTlR4NHpJYUVrCkhTeHR5YU9MVHh0cTJvZFY3S3IzTEdpS3h3UHBuL1QrSWVmK29JcDkyWWNUbitWZkpWR3c0WjNCZXpxYlI4bEEKVWYvK0hGNVpmcE1yVlh0WkQ0SWdzM0kzM0R1djRzQ3VxaEV2TFdUYzQ0cEhpZlZsb296TnhZZlJmVTBDZ1lCTgpIWGE3YTZjSjFZcDgyOWw2MlFsSkt0eDZZbWo5NW9BblF1NUV6MlJPaVpNcVhSTzRudWNPakdVUDU1T3JhYzFhCkZpR20rbUMvc2tGUzBNV2dXOGV2YUhHRGJXVTE4MHdoZVEzNWhXNm9LQWI3bXlSSHRyNHEyMG91RXRRTWRRSUYKc25WMzlHMWl5cWVlQXNmN2R4V0VseWRYcFJpMmI2OGkzQklnemh6ZWJRS0JnUUNkVVF1VHNxVjl5L0pGcHU2SApjNVRWdmhHL3ViZkJzcEk1RGhRcUlHaWpuVkJ6RlQvL1VmSVlNU0tKbzc1cXFCRXlQMkVKU21Dc3VuV3NBRnNNClRzenVpR1RrcktjWnk5RzB3SnFQenRaWmwyRjIrYkpnbkE2bkJFVjdnNVBBNEFmK1FTbWFJaFJ3cUdEQXVST1IKNDdqbmRleUlhTVRORVRFbU9ubXMrYXMxN2c9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
  public.key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzRmxxSnI1VFJza0lRSWdkRTNEZAo3RDlsYm9XZGNUVVQ4YStmSlI3TUF2UW03WFhOb1lrbTN2N01RTDFOWXREdkwybDhDQW5jMFdkU1RJTlU2SVJ2CmM1S3FvMlE0Y3NOWDlTSE9tRWZ6b1JPalFxYWhFY3ZlMWpCWGx1b0NYZFl1WXB4NC8xdGZSZ0c2aWk0VWh4aDYKaUk4cU5NSlFYK2ZMZnFoYmZZZnhCUVZSUHl3QmtBYklQNHgxRUFzYkM2RlNObWtoQ3hpTU5xRWd4YUlwWThDMgprSmRKL1pJVitXVzRub0RkenBLcUhjd21COEZzcnVtbFZZL0ROVnZVU0RJaXBpcTlQYlA0SDk5VFhOMW83NDZvClJhTmEwN3JxMWhvQ2dNU1N5Kzg1U2FnQ294bG15RStEK29mOVNzTVk4T2w5dDByZHpwb2JCdWh5Si9vNWRmdmoKS3dJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t
