spring:  
  profiles:
    active: dev

springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

jwt:
  secret: "qwertyuiopasdfghjklzxcvbnmqwerty"
  expirationMinutes: 120  
#app:
 # security:
  #  authentication:
  #    jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      #  base64-secret: ZDFjZDkyZmFhMjUwNjUyNzdhZWUyMmVkZmFkYzYwODgzZGU0MzBkYzM4MDMyNWE5NzUzZGQyMGNkZmVlNjgxOWFlY2RkOWM1YjVmMWM0YjliOWQ1ZTQ1ODRiOWQ5MWJhYjI4NmFjN2M5MmJiODI5ZDk5MDQwMzIyMDQxYzlmYWQ=
        # Token is valid 24 hours
    #    token-validity-in-seconds: 86400
    #    token-validity-in-seconds-for-remember-me: 2592000